-- ============================================================================
-- Seed Data: Users and Roles for Development/Staging
-- ============================================================================
-- Creates demo users with different roles to showcase authentication,
-- authorization, and per-app RBAC features.
--
-- This seed is used for:
-- - Local development (chat.local.nself.org)
-- - Staging environment (chat.staging.nself.org)
-- - Live demos and testing
--
-- DO NOT run this in production!
-- ============================================================================

-- ============================================================================
-- Register the nchat application
-- ============================================================================
INSERT INTO public.apps (app_id, app_name, app_url, is_active)
VALUES ('nchat', 'ɳChat', 'https://chat.nself.org', true)
ON CONFLICT (app_id) DO UPDATE SET
    app_name = EXCLUDED.app_name,
    app_url = EXCLUDED.app_url,
    updated_at = NOW();

-- ============================================================================
-- Create demo users in auth.users
-- ============================================================================
-- Password for all users: "password" (hashed with bcrypt)
-- bcrypt hash: $2a$10$XJ4J4J4J4J4J4J4J4J4J4Oe9YqKvK9K9K9K9K9K9K9K9K9K9K9K9
--
-- In development, these users can be created via the Nhost Auth API:
-- POST https://auth.local.nself.org/v1/signup/email-password
--
-- The actual user IDs will be generated by Nhost Auth when users sign up.
-- This seed assumes users have already signed up or will sign up through the UI.
--
-- For automated seeding, you would need to:
-- 1. Use Nhost Auth API to create users
-- 2. Get the generated user IDs
-- 3. Assign roles using those IDs
--
-- Below are the expected user accounts:
-- ============================================================================

-- Expected user emails (created via signup):
-- - owner@nself.org
-- - admin@nself.org
-- - mod@nself.org (moderator)
-- - support@nself.org
-- - helper@nself.org
-- - user@nself.org (regular user, no special role)

COMMENT ON COLUMN auth.users.email IS 'User email addresses - see seed file for demo accounts';

-- ============================================================================
-- Helper function to assign role by email
-- ============================================================================
CREATE OR REPLACE FUNCTION assign_role_by_email(
    p_email TEXT,
    p_app_id TEXT,
    p_role TEXT
) RETURNS UUID AS $$
DECLARE
    v_user_id UUID;
    v_role_id UUID;
BEGIN
    -- Find user by email
    SELECT id INTO v_user_id
    FROM auth.users
    WHERE email = p_email AND disabled = false;

    IF v_user_id IS NULL THEN
        RAISE NOTICE 'User not found: %', p_email;
        RETURN NULL;
    END IF;

    -- Assign app role
    INSERT INTO public.app_user_roles (app_id, user_id, role)
    VALUES (p_app_id, v_user_id, p_role)
    ON CONFLICT (app_id, user_id, role) DO UPDATE SET
        updated_at = NOW()
    RETURNING id INTO v_role_id;

    RAISE NOTICE 'Assigned role % to % in app %', p_role, p_email, p_app_id;
    RETURN v_role_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Assign roles to users (run after users have signed up)
-- ============================================================================
-- This section should be run AFTER users have created accounts via the UI
-- or via Nhost Auth API.
--
-- To run this manually after users sign up:
-- SELECT assign_role_by_email('owner@nself.org', 'nchat', 'owner');
-- SELECT assign_role_by_email('admin@nself.org', 'nchat', 'admin');
-- SELECT assign_role_by_email('mod@nself.org', 'nchat', 'moderator');
-- SELECT assign_role_by_email('support@nself.org', 'nchat', 'moderator');
-- SELECT assign_role_by_email('helper@nself.org', 'nchat', 'member');
-- SELECT assign_role_by_email('user@nself.org', 'nchat', 'member');
-- ============================================================================

-- Attempt to assign roles (will succeed only if users exist)
DO $$
BEGIN
    PERFORM assign_role_by_email('owner@nself.org', 'nchat', 'owner');
    PERFORM assign_role_by_email('admin@nself.org', 'nchat', 'admin');
    PERFORM assign_role_by_email('mod@nself.org', 'nchat', 'moderator');
    PERFORM assign_role_by_email('support@nself.org', 'nchat', 'moderator');
    PERFORM assign_role_by_email('helper@nself.org', 'nchat', 'member');
    PERFORM assign_role_by_email('user@nself.org', 'nchat', 'member');
END $$;

-- ============================================================================
-- Create sample channels
-- ============================================================================
INSERT INTO public.nchat_channels (name, description, is_public, created_by)
SELECT
    'General',
    'General discussion for everyone',
    true,
    (SELECT id FROM auth.users WHERE email = 'owner@nself.org' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM auth.users WHERE email = 'owner@nself.org')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.nchat_channels (name, description, is_public, created_by)
SELECT
    'Random',
    'Off-topic conversations and fun',
    true,
    (SELECT id FROM auth.users WHERE email = 'owner@nself.org' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM auth.users WHERE email = 'owner@nself.org')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.nchat_channels (name, description, is_public, created_by)
SELECT
    'Support',
    'Get help from the support team',
    true,
    (SELECT id FROM auth.users WHERE email = 'support@nself.org' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM auth.users WHERE email = 'support@nself.org')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.nchat_channels (name, description, is_public, created_by)
SELECT
    'Announcements',
    'Important announcements and updates',
    true,
    (SELECT id FROM auth.users WHERE email = 'admin@nself.org' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM auth.users WHERE email = 'admin@nself.org')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- Verification query
-- ============================================================================
-- Run this to verify seed data:
--
-- SELECT
--     u.email,
--     aur.role,
--     aur.app_id
-- FROM auth.users u
-- LEFT JOIN public.app_user_roles aur ON u.id = aur.user_id
-- WHERE u.email IN (
--     'owner@nself.org',
--     'admin@nself.org',
--     'mod@nself.org',
--     'support@nself.org',
--     'helper@nself.org',
--     'user@nself.org'
-- )
-- ORDER BY
--     CASE u.email
--         WHEN 'owner@nself.org' THEN 1
--         WHEN 'admin@nself.org' THEN 2
--         WHEN 'mod@nself.org' THEN 3
--         WHEN 'support@nself.org' THEN 4
--         WHEN 'helper@nself.org' THEN 5
--         WHEN 'user@nself.org' THEN 6
--     END;
-- ============================================================================

-- ============================================================================
-- Summary
-- ============================================================================
COMMENT ON TABLE public.app_user_roles IS
'Demo users for local/staging:
- owner@nself.org (owner role) - Full administrative access
- admin@nself.org (admin role) - User and channel management
- mod@nself.org (moderator role) - Content moderation
- support@nself.org (moderator role) - User support
- helper@nself.org (member role) - Regular user helping others
- user@nself.org (member role) - Standard user account

Password for all: "password"

These users showcase:
- Per-app RBAC (different roles per application)
- Authentication with various permission levels
- Real-time features (messaging, typing indicators)
- SSO in monorepo setups (same users across multiple apps)';
