#!/bin/bash

# Generate iOS App Store Screenshots
# This script provides guidance for capturing screenshots

set -e

echo "📸 iOS App Store Screenshot Guide"
echo "=================================="

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}Required Screenshot Sizes:${NC}"
echo "  • 6.7\" Display (iPhone 15 Pro Max, 14 Pro Max, 13 Pro Max, 12 Pro Max)"
echo "    → 1290 x 2796 pixels"
echo ""
echo "  • 6.5\" Display (iPhone 11 Pro Max, 11, XS Max, XR)"
echo "    → 1242 x 2688 pixels"
echo ""
echo "  • 5.5\" Display (iPhone 8 Plus, 7 Plus, 6s Plus)"
echo "    → 1242 x 2208 pixels"
echo ""
echo "  • 12.9\" iPad Pro (6th/5th/4th/3rd gen)"
echo "    → 2048 x 2732 pixels"
echo ""

echo -e "${BLUE}Screenshot Recommendations:${NC}"
echo ""
echo "1. CHANNELS VIEW"
echo "   → Show channel list with several active channels"
echo "   → Display unread badges and recent activity"
echo ""
echo "2. CHAT VIEW"
echo "   → Show a conversation with rich media (images, reactions)"
echo "   → Include thread view if applicable"
echo ""
echo "3. VOICE/VIDEO CALL"
echo "   → Active call screen with controls"
echo "   → Or incoming call notification"
echo ""
echo "4. SEARCH"
echo "   → Search results showing messages across channels"
echo "   → Highlight advanced search filters"
echo ""
echo "5. SETTINGS"
echo "   → User profile or app settings"
echo "   → Show customization options"
echo ""

echo -e "${YELLOW}How to Capture Screenshots:${NC}"
echo ""
echo "Method 1: Using Xcode Simulator"
echo "  1. Open the iOS app in Xcode"
echo "  2. Select simulator: iPhone 15 Pro Max"
echo "  3. Run the app (Cmd+R)"
echo "  4. Navigate to each screen"
echo "  5. Capture: Cmd+S or File > New Screen Shot"
echo "  6. Screenshots saved to Desktop"
echo ""
echo "Method 2: Using Physical Device"
echo "  1. Connect iPhone to Mac"
echo "  2. Build and run on device"
echo "  3. Take screenshots: Volume Up + Side Button"
echo "  4. Transfer via AirDrop or Photos app"
echo ""
echo "Method 3: Using fastlane snapshot (automated)"
echo "  1. Install fastlane: brew install fastlane"
echo "  2. Run: fastlane snapshot"
echo "  3. Screenshots generated for all devices"
echo ""

echo -e "${GREEN}Screenshot Naming Convention:${NC}"
echo "  screenshot_1_channels_67.png      # 6.7\" display"
echo "  screenshot_2_chat_67.png"
echo "  screenshot_3_calls_67.png"
echo "  screenshot_4_search_67.png"
echo "  screenshot_5_settings_67.png"
echo ""
echo "  screenshot_1_channels_65.png      # 6.5\" display"
echo "  screenshot_2_chat_65.png"
echo "  ..."
echo ""

echo -e "${BLUE}Best Practices:${NC}"
echo "  ✓ Use demo data with realistic content"
echo "  ✓ Show the app in use (not empty states)"
echo "  ✓ Include dark mode screenshots if supported"
echo "  ✓ Highlight unique features"
echo "  ✓ Keep text readable (avoid tiny fonts)"
echo "  ✓ Use status bar with full signal/battery"
echo "  ✓ 9:41 AM is the standard time in iOS screenshots"
echo ""

echo -e "${YELLOW}Output Directory:${NC}"
SCREENSHOT_DIR="../metadata/ios/screenshots"
mkdir -p "$SCREENSHOT_DIR"
echo "  $SCREENSHOT_DIR"
echo ""

echo -e "${GREEN}Next Steps:${NC}"
echo "  1. Capture screenshots using methods above"
echo "  2. Save to: $SCREENSHOT_DIR"
echo "  3. Update metadata/ios/app-store-metadata.json"
echo "  4. Upload to App Store Connect"
echo ""

echo "📝 For automated screenshot generation, use:"
echo "   cd platforms/capacitor/ios"
echo "   fastlane snapshot"
echo ""
